# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z59tj_TB74rlkcOlJR_Qfk1FBQg3KEpN

N NCOBELA 22423967
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import io

df = pd.read_csv("/content/drive/MyDrive/Data/forecast.csv")

st.set_page_config(
    page_title="Forecast Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state = "expanded")

def main():
    st.title("Forecast Analysis Dashboard")
    st.sidebar.header("Data Upload")
    upload_file = st.sidebar.file_uploader("/content/drive/MyDrive/Data/forecast.csv", type=["csv"])

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Upload = files.upload

filename = list(Upload.keys())[0]
df = pd.read_csv(filename)
df['ds']=pd.to_datetime(df['ds'])

print("Forecast Amalysis Dhasboard")
print(f"Dta from{df['ds'].min()}to {df['ds'].max}")
print(f"Total records: {len(df)}")


plt.figure(figsize=(12,6))
plt.plot(df['ds'],df['yhat'],label='Forecast')
plt.fill_between(df['ds'],df['yhat_lower'],df['yhat_upper'], alpha= 0.3)

plt.title('Forecast Over Time')
plt.xticks(rotation=45)
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend()
plt.tight_layout()
plt.show()